package atonix.youquote.UI.desktop;

import atonix.youquote.BusinessLogic.Telecharger;
import atonix.youquote.BusinessLogic.CSVFile;
import atonix.youquote.BusinessLogic.RecupFichiers;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.nio.channels.Channels;
import java.nio.channels.ReadableByteChannel;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ankat
 */
public class FrameYouQuote extends javax.swing.JFrame { 
    
    /**
     * Creates new form FrameYouQuote
     */
    public FrameYouQuote() {
        initComponents();
    } /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panPrincipal = new javax.swing.JPanel();
        panOHLCV = new javax.swing.JPanel();
        lblOpenQuote = new javax.swing.JLabel();
        lblHigh = new javax.swing.JLabel();
        lblLow = new javax.swing.JLabel();
        lblCloseQuote = new javax.swing.JLabel();
        lblVariation = new javax.swing.JLabel();
        panFiche = new javax.swing.JPanel();
        lblPhoto = new javax.swing.JLabel();
        comboNoms = new javax.swing.JComboBox();
        buttonRecherche = new javax.swing.JButton();
        textQuote = new javax.swing.JTextField();
        panRatios = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        panOHLCV.setBackground(new java.awt.Color(255, 255, 255));

        lblOpenQuote.setText("...");
        lblOpenQuote.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Open", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));
        lblOpenQuote.setPreferredSize(new java.awt.Dimension(30, 30));

        lblHigh.setText("...");
        lblHigh.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "High", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));
        lblHigh.setPreferredSize(new java.awt.Dimension(30, 30));

        lblLow.setText("...");
        lblLow.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Low", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));
        lblLow.setPreferredSize(new java.awt.Dimension(30, 30));

        lblCloseQuote.setText("...");
        lblCloseQuote.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Close", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));
        lblCloseQuote.setPreferredSize(new java.awt.Dimension(30, 30));

        lblVariation.setText("...");
        lblVariation.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Variation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));
        lblVariation.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout panOHLCVLayout = new javax.swing.GroupLayout(panOHLCV);
        panOHLCV.setLayout(panOHLCVLayout);
        panOHLCVLayout.setHorizontalGroup(
            panOHLCVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panOHLCVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panOHLCVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblVariation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                    .addComponent(lblLow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panOHLCVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblOpenQuote, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                        .addComponent(lblHigh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblCloseQuote, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(65, 65, 65))
        );
        panOHLCVLayout.setVerticalGroup(
            panOHLCVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panOHLCVLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblOpenQuote, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHigh, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLow, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCloseQuote, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblVariation, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panFiche.setBackground(new java.awt.Color(255, 255, 255));

        lblPhoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        comboNoms.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboNoms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNomsActionPerformed(evt);
            }
        });

        buttonRecherche.setText("Rechercher\n");
        buttonRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRechercheActionPerformed(evt);
            }
        });

        textQuote.setText("Saisissez...");
        textQuote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textQuoteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panFicheLayout = new javax.swing.GroupLayout(panFiche);
        panFiche.setLayout(panFicheLayout);
        panFicheLayout.setHorizontalGroup(
            panFicheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFicheLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(panFicheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textQuote, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addComponent(comboNoms, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonRecherche)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        panFicheLayout.setVerticalGroup(
            panFicheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFicheLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(panFicheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textQuote, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonRecherche))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboNoms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        panRatios.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panRatiosLayout = new javax.swing.GroupLayout(panRatios);
        panRatios.setLayout(panRatiosLayout);
        panRatiosLayout.setHorizontalGroup(
            panRatiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panRatiosLayout.setVerticalGroup(
            panRatiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 104, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panPrincipalLayout = new javax.swing.GroupLayout(panPrincipal);
        panPrincipal.setLayout(panPrincipalLayout);
        panPrincipalLayout.setHorizontalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panPrincipalLayout.createSequentialGroup()
                .addComponent(panFiche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panOHLCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(panRatios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panPrincipalLayout.setVerticalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPrincipalLayout.createSequentialGroup()
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panFiche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panOHLCV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panRatios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRechercheActionPerformed
        
        // Récupère le fichier Yahoo
        RecupFichiers.recupFichierYahoo(textQuote.getText());
        
        // Parse le fichier csv
        try {
            CSVFile.parseCSV();      
        } catch (Exception ex) {
            Logger.getLogger(FrameYouQuote.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        // Mise à jour des labels avec les données parsées
        lblOpenQuote.setText(CSVFile.data[0].toString()) ;
        lblHigh.setText(CSVFile.data[1].toString());
        lblLow.setText(CSVFile.data[2].toString());
        lblCloseQuote.setText(CSVFile.data[3].toString());
        lblVariation.setText((CSVFile.variation(CSVFile.data[0], CSVFile.data[3])).toString());
        
        /*
                  try {
                       fichier = new Telecharger(url) ;
                  } catch (MalformedURLException ex) {
                      Logger.getLogger(FrameYouQuote.class.getName()).log(Level.SEVERE, null, ex);
                  } catch (IOException ex) {
                      Logger.getLogger(FrameYouQuote.class.getName()).log(Level.SEVERE, null, ex);
                  }
                    */
        
    }//GEN-LAST:event_buttonRechercheActionPerformed

    private void comboNomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNomsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboNomsActionPerformed

    private void textQuoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textQuoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textQuoteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameYouQuote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameYouQuote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameYouQuote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameYouQuote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameYouQuote().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonRecherche;
    private javax.swing.JComboBox comboNoms;
    private javax.swing.JLabel lblCloseQuote;
    private javax.swing.JLabel lblHigh;
    private javax.swing.JLabel lblLow;
    private javax.swing.JLabel lblOpenQuote;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblVariation;
    private javax.swing.JPanel panFiche;
    private javax.swing.JPanel panOHLCV;
    private javax.swing.JPanel panPrincipal;
    private javax.swing.JPanel panRatios;
    private javax.swing.JTextField textQuote;
    // End of variables declaration//GEN-END:variables
}